require('dotenv').config();
const path=require('path'),fs=require('fs'),crypto=require('crypto');
const express=require('express'),helmet=require('helmet'),morgan=require('morgan'),rateLimit=require('express-rate-limit'),Database=require('better-sqlite3'),nodemailer=require('nodemailer');
const app=express(),PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'0.0.0.0',BASE=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,''),OWNER=process.env.OWNER_EMAIL||'dineshmca500@gmail.com',ADMIN=process.env.ADMIN_TOKEN||'change-this-admin-token',WA=process.env.WHATSAPP_NUMBER||'';
const dbPath=process.env.DB_PATH||path.join(__dirname,'data','bookings.db');fs.mkdirSync(path.dirname(dbPath),{recursive:true});const db=new Database(dbPath);db.pragma('journal_mode=WAL');db.exec(`CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,country TEXT NOT NULL,visa TEXT NOT NULL,whatsapp TEXT NOT NULL,requirement TEXT NOT NULL,message TEXT DEFAULT '',booking_date TEXT NOT NULL,booking_time TEXT NOT NULL,timezone TEXT DEFAULT 'America/New_York',status TEXT DEFAULT 'new',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS active_slot ON bookings(booking_date,booking_time) WHERE status <> 'cancelled';`);
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:true}));app.use(morgan('combined'));app.use('/api/',rateLimit({windowMs:15*60*1000,limit:120,standardHeaders:'draft-8',legacyHeaders:false}));app.use(express.static(__dirname));
const TIMES=['10:00 AM ET','11:30 AM ET','1:00 PM ET','3:00 PM ET','5:30 PM ET','7:00 PM ET'];const pad=n=>String(n).padStart(2,'0');
function days(n=10){const a=[],d=new Date();while(a.length<n){d.setDate(d.getDate()+1);if(d.getDay()>0&&d.getDay()<6)a.push(new Date(d))}return a}function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function label(d){return d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}function clean(v,n=300){return String(v??'').trim().slice(0,n)}
function available(date){const booked=new Set(db.prepare("SELECT booking_time FROM bookings WHERE booking_date=? AND status!='cancelled'").all(date).map(x=>x.booking_time));return TIMES.map(time=>({time,available:!booked.has(time)}))}
function wa(text){return WA?`https://wa.me/${WA.replace(/\D/g,'')}?text=${encodeURIComponent(text)}`:null}
let mailer=null;if(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS)mailer=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});
async function email(b){if(!mailer)return false;await mailer.sendMail({from:process.env.SMTP_FROM||OWNER,to:OWNER,subject:`New USA Job Marketing Call — ${b.name}`,text:`New booking\n\nCandidate: ${b.name}\nCountry: ${b.country}\nVisa: ${b.visa}\nWhatsApp: ${b.whatsapp}\nRequirement: ${b.requirement}\nDate: ${b.booking_date}\nTime: ${b.booking_time} ET\nMessage: ${b.message||'Not provided'}\n\nCalendar: ${BASE}/api/bookings/${b.public_id}/ics`});return true}
app.get('/api/health',(q,r)=>r.json({ok:true,service:'usa-job-marketing'}));
app.get('/api/slots',(q,r)=>r.json({timezone:'America/New_York',dates:days().map(d=>({date:iso(d),label:label(d),slots:available(iso(d))}))}));
app.post('/api/bookings',async(q,r)=>{try{const b={name:clean(q.body.name,100),country:clean(q.body.country,60),visa:clean(q.body.visa,80),whatsapp:clean(q.body.whatsapp,40),requirement:clean(q.body.requirement,80),message:clean(q.body.message,1000),booking_date:clean(q.body.booking_date,10),booking_time:clean(q.body.booking_time,30)};if(Object.values(b).some((v,i)=>!v&&i!==6))return r.status(400).json({error:'Please complete all required fields.'});if(!/^\d{4}-\d{2}-\d{2}$/.test(b.booking_date)||!TIMES.includes(b.booking_time)||!days().some(d=>iso(d)===b.booking_date))return r.status(400).json({error:'Invalid or unavailable slot.'});b.public_id=crypto.randomBytes(8).toString('hex');const now=new Date().toISOString();try{db.prepare(`INSERT INTO bookings(public_id,name,country,visa,whatsapp,requirement,message,booking_date,booking_time,timezone,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'America/New_York','new',?,?)`).run(b.public_id,b.name,b.country,b.visa,b.whatsapp,b.requirement,b.message,b.booking_date,b.booking_time,now,now)}catch(e){if(String(e.message).includes('UNIQUE'))return r.status(409).json({error:'That slot was just booked. Please choose another slot.'});throw e}b.timezone='America/New_York';b.status='new';let sent=false;try{sent=await email(b)}catch(e){console.error(e.message)}const text=`Hi Dinesh, I booked a USA Job Marketing call. Name: ${b.name}. Requirement: ${b.requirement}. Slot: ${label(new Date(b.booking_date+'T12:00:00'))} • ${b.booking_time}. Booking ID: ${b.public_id}`;r.status(201).json({ok:true,booking:b,email_sent:sent,calendar_url:`${BASE}/api/bookings/${b.public_id}/ics`,whatsapp_url:wa(text)})}catch(e){console.error(e);r.status(500).json({error:'Unable to create booking right now.'})}});
function auth(q,r,n){if(q.query.token!==ADMIN&&q.get('x-admin-token')!==ADMIN)return r.status(401).json({error:'Unauthorized'});n()}app.get('/api/admin/bookings',auth,(q,r)=>{const s=clean(q.query.status,20);const rows=s?db.prepare('SELECT * FROM bookings WHERE status=? ORDER BY booking_date,booking_time').all(s):db.prepare('SELECT * FROM bookings ORDER BY booking_date,booking_time').all();r.json({bookings:rows})});app.patch('/api/admin/bookings/:id',auth,(q,r)=>{const s=clean(q.body.status,20);if(!['new','confirmed','completed','cancelled'].includes(s))return r.status(400).json({error:'Invalid status'});const x=db.prepare('UPDATE bookings SET status=?,updated_at=? WHERE public_id=?').run(s,new Date().toISOString(),clean(q.params.id,50));r.json(x.changes?{ok:true}:{error:'Booking not found'})});
app.get('/api/bookings/:id/ics',(q,r)=>{const b=db.prepare('SELECT * FROM bookings WHERE public_id=?').get(clean(q.params.id,50));if(!b)return r.status(404).send('Booking not found');const [y,m,d]=b.booking_date.split('-');const hm=b.booking_time.match(/(\d+):(\d+)\s*(AM|PM)/i);let h=Number(hm[1]),min=Number(hm[2]);if(hm[3].toUpperCase()==='PM'&&h<12)h+=12;if(hm[3].toUpperCase()==='AM'&&h===12)h=0;const start=`${y}${m}${d}T${pad(h)}${pad(min)}00`,end=`${y}${m}${d}T${pad(h+(min+30>=60?1:0))}${pad((min+30)%60)}00`;const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Dinesh Yadav//USA Job Marketing//EN','BEGIN:VEVENT',`UID:${b.public_id}@${q.hostname}`,`DTSTAMP:${new Date().toISOString().replace(/[-:.]/g,'').replace(/\d{3}Z$/,'Z')}`,`DTSTART;TZID=America/New_York:${start}`,`DTEND;TZID=America/New_York:${end}`,'SUMMARY:USA Job Application Marketing Strategy Call',`DESCRIPTION:${clean(b.requirement+' - '+b.message,900).replace(/[\r\n,;]/g,' ')}`,'LOCATION:Online / WhatsApp',`STATUS:${b.status==='cancelled'?'CANCELLED':'CONFIRMED'}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');r.set({'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':`attachment; filename="usa-job-call-${b.public_id}.ics"`}).send(ics)});
app.get('/admin',(q,r)=>r.sendFile(path.join(__dirname,'admin.html')));app.get('/{*splat}',(q,r)=>r.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,HOST,()=>console.log(`USA Job Marketing running at ${HOST}:${PORT}`));
