require('dotenv').config();
const path=require('path'),fs=require('fs'),crypto=require('crypto');
const express=require('express'),helmet=require('helmet'),morgan=require('morgan'),rateLimit=require('express-rate-limit'),Database=require('better-sqlite3'),nodemailer=require('nodemailer'),multer=require('multer'),pdfParse=require('pdf-parse'),mammoth=require('mammoth');
const app=express(),PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||'0.0.0.0',BASE=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,''),OWNER=process.env.OWNER_EMAIL||'dineshmca500@gmail.com',ADMIN=process.env.ADMIN_TOKEN||'change-this-admin-token',WA=process.env.WHATSAPP_NUMBER||'';
const TZ='America/New_York';
const dbPath=process.env.DB_PATH||path.join(__dirname,'data','bookings.db');fs.mkdirSync(path.dirname(dbPath),{recursive:true});const db=new Database(dbPath);db.pragma('journal_mode=WAL');db.exec(`CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,country TEXT NOT NULL,visa TEXT NOT NULL,whatsapp TEXT NOT NULL,requirement TEXT NOT NULL,message TEXT DEFAULT '',booking_date TEXT NOT NULL,booking_time TEXT NOT NULL,timezone TEXT DEFAULT 'America/New_York',status TEXT DEFAULT 'new',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS active_slot ON bookings(booking_date,booking_time) WHERE status <> 'cancelled';CREATE TABLE IF NOT EXISTS resume_intakes(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,whatsapp TEXT DEFAULT '',target_role TEXT DEFAULT '',country TEXT DEFAULT '',file_name TEXT NOT NULL,file_path TEXT NOT NULL,file_size INTEGER NOT NULL,mime_type TEXT NOT NULL,status TEXT DEFAULT 'received',created_at TEXT NOT NULL);`);
const resumeColumns=[['parsed_text','TEXT DEFAULT ""'],['ats_score','INTEGER DEFAULT 0'],['keyword_match','INTEGER DEFAULT 0'],['missing_keywords','TEXT DEFAULT ""'],['matched_keywords','TEXT DEFAULT ""'],['portfolio_slug','TEXT DEFAULT ""']];for(const [c,t] of resumeColumns){try{db.exec(`ALTER TABLE resume_intakes ADD COLUMN ${c} ${t}`)}catch(e){if(!String(e.message).includes('duplicate column'))throw e}}
const uploadDir=process.env.RESUME_DIR||path.join(__dirname,'data','resumes');fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();cb(null,`${Date.now()}-${crypto.randomBytes(8).toString('hex')}${ext}`)}});
const resumeUpload=multer({storage,limits:{fileSize:8*1024*1024,files:1},fileFilter:(req,file,cb)=>{const ok=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(file.mimetype)||/\.(pdf|doc|docx)$/i.test(file.originalname);cb(ok?null:new Error('Please upload a PDF, DOC or DOCX resume.'),ok)}});
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:true}));app.use(morgan('combined'));app.use('/api/',rateLimit({windowMs:15*60*1000,limit:120,standardHeaders:'draft-8',legacyHeaders:false}));app.use(express.static(__dirname));
const TIMES=['10:00 AM ET','11:30 AM ET','1:00 PM ET','3:00 PM ET','5:30 PM ET','7:00 PM ET'];const pad=n=>String(n).padStart(2,'0');
function nyParts(date=new Date()){const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);return Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]))}
function nyDateKey(date=new Date()){const p=nyParts(date);return `${p.year}-${p.month}-${p.day}`}
function addNYDays(key,daysToAdd){const [y,m,d]=key.split('-').map(Number);const x=new Date(Date.UTC(y,m-1,d+daysToAdd,12));return `${x.getUTCFullYear()}-${pad(x.getUTCMonth()+1)}-${pad(x.getUTCDate())}`}
function days(n=10){const a=[],today=nyDateKey();for(let i=1;a.length<n;i++){const key=addNYDays(today,i);const [y,m,d]=key.split('-').map(Number);const weekday=new Date(Date.UTC(y,m-1,d,12)).getUTCDay();if(weekday>0&&weekday<6)a.push({key,y,m,d})}return a}
function label(d){const key=d.key||d;const [y,m,day]=key.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'short',month:'short',day:'numeric'}).format(new Date(Date.UTC(y,m-1,day,12)))}function clean(v,n=300){return String(v??'').trim().slice(0,n)}
function available(date){const booked=new Set(db.prepare("SELECT booking_time FROM bookings WHERE booking_date=? AND status!='cancelled'").all(date).map(x=>x.booking_time));return TIMES.map(time=>({time,available:!booked.has(time)}))}
function wa(text){return WA?`https://wa.me/${WA.replace(/\D/g,'')}?text=${encodeURIComponent(text)}`:null}
let mailer=null;if(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS)mailer=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});
async function email(b){if(!mailer)return false;await mailer.sendMail({from:process.env.SMTP_FROM||OWNER,to:OWNER,subject:`New USA Job Marketing Call — ${b.name}`,text:`New booking\n\nCandidate: ${b.name}\nCountry: ${b.country}\nVisa: ${b.visa}\nWhatsApp: ${b.whatsapp}\nRequirement: ${b.requirement}\nDate: ${b.booking_date}\nTime: ${b.booking_time} (USA Eastern Time)\nMessage: ${b.message||'Not provided'}\n\nCalendar: ${BASE}/api/bookings/${b.public_id}/ics`});return true}
const SKILLS=['Java','JavaScript','TypeScript','Python','C++','C#','Go','React','Angular','Node.js','Spring Boot','Spring','AWS','Azure','GCP','Docker','Kubernetes','Terraform','Kafka','SQL','PostgreSQL','MySQL','MongoDB','Redis','Microservices','REST API','GraphQL','Git','Jenkins','CI/CD','Linux','DevOps','SRE','Cybersecurity','Data Engineering','Machine Learning','AI','Tableau','Power BI','Spark','Databricks','Salesforce'];
const SECTION_WORDS=['experience','work experience','professional experience','education','skills','summary','profile','projects','certifications','technical skills'];
function normalizeText(t){return String(t||'').replace(/\u0000/g,' ').replace(/\r/g,'\n').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim()}
function findSkills(text){const low=text.toLowerCase();return SKILLS.filter(s=>low.includes(s.toLowerCase())).slice(0,30)}
function scoreResume(text,role){const low=text.toLowerCase(),matched=findSkills(text);const roleWords=String(role||'').toLowerCase().split(/[^a-z0-9+#.]+/).filter(x=>x.length>2);const roleHits=roleWords.filter(w=>low.includes(w));const sections=SECTION_WORDS.filter(w=>low.includes(w));const contact=/(\+?\d[\d\s().-]{7,})/.test(text)&&/@[^\s@]+\.[^\s@]+/.test(text);const bullets=(text.match(/[•●▪◦]|\n\s*[-*]/g)||[]).length;let score=35+Math.min(25,matched.length*2)+Math.min(15,sections.length*2)+Math.min(10,roleHits.length*3)+(contact?10:0)+(bullets?5:0);score=Math.max(0,Math.min(98,score));const target=[...new Set([...roleWords.map(x=>x.replace(/^\W+|\W+$/g,'')),...SKILLS.slice(0,12).map(x=>x.toLowerCase())])].filter(Boolean);const missing=target.filter(w=>!low.includes(w)).slice(0,8);return {ats_score:score,keyword_match:target.length?Math.round(((target.length-missing.length)/target.length)*100):0,matched_keywords:matched,missing_keywords:missing,signals:{contact,sections,bullets,role_hits:roleHits}}}
async function extractResume(file){const ext=path.extname(file.originalname).toLowerCase();if(ext==='.pdf'){const data=await pdfParse(fs.readFileSync(file.path));return normalizeText(data.text)}if(ext==='.docx'){const data=await mammoth.extractRawText({path:file.path});return normalizeText(data.value)}return normalizeText(fs.readFileSync(file.path,'utf8'))}
function portfolioSlug(name,id){return `${String(name||'candidate').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45)||'candidate'}-${id.slice(0,8)}`}
app.get('/api/health',(q,r)=>r.json({ok:true,service:'shavya-talent-recruitment',timezone:TZ,resume_intelligence:true}));
app.get('/api/slots',(q,r)=>r.json({timezone:TZ,timezone_label:'USA Eastern Time (ET)',dates:days().map(d=>({date:d.key,label:label(d),slots:available(d.key)}))}));
app.post('/api/bookings',async(q,r)=>{try{const b={name:clean(q.body.name,100),country:clean(q.body.country,60),visa:clean(q.body.visa,80),whatsapp:clean(q.body.whatsapp,40),requirement:clean(q.body.requirement,80),message:clean(q.body.message,1000),booking_date:clean(q.body.booking_date,10),booking_time:clean(q.body.booking_time,30)};if(Object.values(b).some((v,i)=>!v&&i!==6))return r.status(400).json({error:'Please complete all required fields.'});if(!/^\d{4}-\d{2}-\d{2}$/.test(b.booking_date)||!TIMES.includes(b.booking_time)||!days().some(d=>d.key===b.booking_date))return r.status(400).json({error:'Invalid or unavailable USA Eastern Time slot.'});b.public_id=crypto.randomBytes(8).toString('hex');const now=new Date().toISOString();try{db.prepare(`INSERT INTO bookings(public_id,name,country,visa,whatsapp,requirement,message,booking_date,booking_time,timezone,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'America/New_York','new',?,?)`).run(b.public_id,b.name,b.country,b.visa,b.whatsapp,b.requirement,b.message,b.booking_date,b.booking_time,now,now)}catch(e){if(String(e.message).includes('UNIQUE'))return r.status(409).json({error:'That slot was just booked. Please choose another slot.'});throw e}b.timezone=TZ;b.status='new';let sent=false;try{sent=await email(b)}catch(e){console.error(e.message)}const text=`Hi Dinesh, I booked a USA Job Marketing call. Name: ${b.name}. Requirement: ${b.requirement}. Slot: ${label({key:b.booking_date})} • ${b.booking_time} (USA Eastern Time). Booking ID: ${b.public_id}`;r.status(201).json({ok:true,booking:b,email_sent:sent,calendar_url:`${BASE}/api/bookings/${b.public_id}/ics`,whatsapp_url:wa(text)})}catch(e){console.error(e);r.status(500).json({error:'Unable to create booking right now.'})}});
app.post('/api/resume-intake',(req,res)=>{resumeUpload.single('resume')(req,res,async err=>{if(err){const msg=err.code==='LIMIT_FILE_SIZE'?'Resume must be 8 MB or smaller.':err.message||'Resume upload failed.';return res.status(400).json({error:msg})}try{const name=clean(req.body.name,100),emailAddr=clean(req.body.email,160),whatsapp=clean(req.body.whatsapp,40),targetRole=clean(req.body.target_role,120),country=clean(req.body.country,60);if(!name||!emailAddr||!req.file)return res.status(400).json({error:'Name, email and resume are required.'});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailAddr)){if(req.file)fs.unlinkSync(req.file.path);return res.status(400).json({error:'Please enter a valid email address.'})}const publicId=crypto.randomBytes(8).toString('hex'),now=new Date().toISOString();let parsedText='',analysis={ats_score:0,keyword_match:0,matched_keywords:[],missing_keywords:[],signals:{}};try{parsedText=await extractResume(req.file);analysis=scoreResume(parsedText,targetRole)}catch(e){console.error('Resume parsing:',e.message)}const slug=portfolioSlug(name,publicId);db.prepare('INSERT INTO resume_intakes(public_id,name,email,whatsapp,target_role,country,file_name,file_path,file_size,mime_type,status,created_at,parsed_text,ats_score,keyword_match,missing_keywords,matched_keywords,portfolio_slug) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(publicId,name,emailAddr,whatsapp,targetRole,country,req.file.originalname,req.file.path,req.file.size,req.file.mimetype,'analyzed',now,parsedText,analysis.ats_score,analysis.keyword_match,JSON.stringify(analysis.missing_keywords),JSON.stringify(analysis.matched_keywords),slug);if(mailer){try{await mailer.sendMail({from:process.env.SMTP_FROM||OWNER,to:OWNER,subject:`Resume Intelligence Report — ${name}`,text:`Resume review request\n\nName: ${name}\nEmail: ${emailAddr}\nWhatsApp: ${whatsapp||'Not provided'}\nCountry: ${country||'Not provided'}\nTarget role: ${targetRole||'Not provided'}\nFile: ${req.file.originalname}\nReview ID: ${publicId}\nATS-style score: ${analysis.ats_score}/100\nKeyword match: ${analysis.keyword_match}%\nMatched: ${analysis.matched_keywords.join(', ')||'None'}\nMissing suggestions: ${analysis.missing_keywords.join(', ')||'None'}\nPortfolio preview: ${BASE}/portfolio/${slug}`})}catch(e){console.error('Resume email:',e.message)}}res.status(201).json({ok:true,public_id:publicId,analysis:{ats_score:analysis.ats_score,keyword_match:analysis.keyword_match,matched_keywords:analysis.matched_keywords,missing_keywords:analysis.missing_keywords,signals:analysis.signals},portfolio_url:`${BASE}/portfolio/${slug}`,message:'Resume analyzed for ATS readiness, keyword alignment and digital-profile opportunities.'})}catch(e){if(req.file?.path&&fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);console.error(e);res.status(500).json({error:'Unable to analyze the resume right now.'})}})});
app.get('/api/resume-intake/:id',async(q,r)=>{const x=db.prepare('SELECT public_id,name,target_role,country,file_name,file_size,ats_score,keyword_match,missing_keywords,matched_keywords,status,created_at,portfolio_slug FROM resume_intakes WHERE public_id=?').get(clean(q.params.id,50));if(!x)return r.status(404).json({error:'Resume review not found'});r.json({resume:{...x,missing_keywords:JSON.parse(x.missing_keywords||'[]'),matched_keywords:JSON.parse(x.matched_keywords||'[]')}})});
app.get('/portfolio/:slug',(q,r)=>{const x=db.prepare('SELECT * FROM resume_intakes WHERE portfolio_slug=?').get(clean(q.params.slug,100));if(!x)return r.status(404).send('Portfolio not found');const skills=JSON.parse(x.matched_keywords||'[]').slice(0,12);r.type('html').send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${clean(x.name,80)} | Shavya Talent Recruitment</title><style>body{margin:0;background:#f4f8ff;color:#10233f;font-family:Arial,sans-serif}.wrap{max-width:900px;margin:50px auto;padding:24px}.card{background:white;border:1px solid #dbe6f4;border-radius:24px;padding:36px;box-shadow:0 18px 60px #12315a14}h1{font-size:42px;margin:0 0 8px}h2{margin-top:32px}.tag{display:inline-block;padding:8px 12px;margin:4px;border-radius:999px;background:#eaf3ff;color:#1267e8}.score{font-size:44px;font-weight:800;color:#1267e8}.muted{color:#61738c}</style></head><body><div class="wrap"><div class="card"><p class="muted">SHAVYA TALENT RECRUITMENT · DIGITAL PROFILE</p><h1>${clean(x.name,80)}</h1><p>${clean(x.target_role||'Professional Profile',120)} · ${clean(x.country||'USA Market',60)}</p><div class="score">${x.ats_score}/100</div><p class="muted">ATS readiness snapshot · Keyword alignment ${x.keyword_match}%</p><h2>Skills & Keywords</h2><div>${skills.map(s=>`<span class="tag">${clean(s,40)}</span>`).join('')}</div><p class="muted">This digital profile is generated from a candidate-submitted resume. It is a profile preview, not an employment guarantee or endorsement.</p></div></div></body></html>`)});
function auth(q,r,n){if(q.query.token!==ADMIN&&q.get('x-admin-token')!==ADMIN)return r.status(401).json({error:'Unauthorized'});n()}app.get('/api/admin/bookings',auth,(q,r)=>{const s=clean(q.query.status,20);const rows=s?db.prepare('SELECT * FROM bookings WHERE status=? ORDER BY booking_date,booking_time').all(s):db.prepare('SELECT * FROM bookings ORDER BY booking_date,booking_time').all();r.json({bookings:rows})});app.get('/api/admin/resumes',auth,(q,r)=>{const rows=db.prepare('SELECT id,public_id,name,email,whatsapp,target_role,country,file_name,file_size,mime_type,status,ats_score,keyword_match,missing_keywords,matched_keywords,portfolio_slug,created_at FROM resume_intakes ORDER BY created_at DESC').all();r.json({resumes:rows})});app.patch('/api/admin/bookings/:id',auth,(q,r)=>{const s=clean(q.body.status,20);if(!['new','confirmed','completed','cancelled'].includes(s))return r.status(400).json({error:'Invalid status'});const x=db.prepare('UPDATE bookings SET status=?,updated_at=? WHERE public_id=?').run(s,new Date().toISOString(),clean(q.params.id,50));r.json(x.changes?{ok:true}:{error:'Booking not found'})});
app.get('/api/bookings/:id/ics',(q,r)=>{const b=db.prepare('SELECT * FROM bookings WHERE public_id=?').get(clean(q.params.id,50));if(!b)return r.status(404).send('Booking not found');const [y,m,d]=b.booking_date.split('-');const hm=b.booking_time.match(/(\d+):(\d+)\s*(AM|PM)/i);let h=Number(hm[1]),min=Number(hm[2]);if(hm[3].toUpperCase()==='PM'&&h<12)h+=12;if(hm[3].toUpperCase()==='AM'&&h===12)h=0;const start=`${y}${m}${d}T${pad(h)}${pad(min)}00`,end=`${y}${m}${d}T${pad(h+(min+30>=60?1:0))}${pad((min+30)%60)}00`;const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Shavya Talent Recruitment//EN','BEGIN:VEVENT',`UID:${b.public_id}@${q.hostname}`,`DTSTAMP:${new Date().toISOString().replace(/[-:.]/g,'').replace(/\d{3}Z$/,'Z')}`,`DTSTART;TZID=America/New_York:${start}`,`DTEND;TZID=America/New_York:${end}`,'SUMMARY:Shavya Talent Recruitment Strategy Call',`DESCRIPTION:${clean(b.requirement+' - '+b.message,900).replace(/[\r\n,;]/g,' ')}`,'LOCATION:Online / WhatsApp',`STATUS:${b.status==='cancelled'?'CANCELLED':'CONFIRMED'}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');r.set({'Content-Type':'text/calendar; charset=utf-8','Content-Disposition':`attachment; filename="usa-job-call-${b.public_id}.ics"`}).send(ics)});
app.get('/admin',(q,r)=>r.sendFile(path.join(__dirname,'admin.html')));app.get('/{*splat}',(q,r)=>r.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,HOST,()=>console.log(`Shavya Talent Recruitment running at ${HOST}:${PORT} · ${TZ}`));
