const form=document.getElementById('bookingForm');const selectedSlot=document.getElementById('selectedSlot');const toast=document.getElementById('toast');const slotsWrap=document.getElementById('slots');const datesWrap=document.querySelector('.date-row');let chosenDate='',chosenTime='';
async function loadAvailability(){try{const r=await fetch('/api/slots');const data=await r.json();datesWrap.innerHTML=data.dates.slice(0,5).map((d,i)=>{const dt=new Date(d.date+'T12:00:00');return `<button type="button" class="date-btn ${i===0?'active':''}" data-date="${d.date}">${dt.getDate()}<br><small>${dt.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}</small></button>`}).join('');chosenDate=data.dates[0]?.date||'';renderSlots(data.dates[0]?.slots||[]);bindDates(data.dates)}catch(e){selectedSlot.textContent='Unable to load slots'}}
function bindDates(all){document.querySelectorAll('.date-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.date-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');chosenDate=btn.dataset.date;chosenTime='';renderSlots(all.find(x=>x.date===chosenDate)?.slots||[]);updateSlotLabel()}))}
function renderSlots(items){slotsWrap.innerHTML=items.map(x=>`<button type="button" data-time="${x.time}" ${x.available?'':'disabled'}>${x.time}${x.available?'':' • Booked'}</button>`).join('');slotsWrap.querySelectorAll('button:not(:disabled)').forEach(btn=>btn.addEventListener('click',()=>{slotsWrap.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');chosenTime=btn.dataset.time;updateSlotLabel()}))}
function updateSlotLabel(){selectedSlot.textContent=chosenTime?`${chosenDate} • ${chosenTime}`:'Select a time slot';selectedSlot.style.color=''}

const roadmapSteps=[...document.querySelectorAll('.roadmap-step')];const roadmapProgress=document.getElementById('roadmapProgress');if(roadmapSteps.length){const roadObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');e.target.classList.toggle('active',true);const i=roadmapSteps.indexOf(e.target);roadmapSteps.forEach((s,n)=>s.classList.toggle('active',n<=i));if(roadmapProgress){const pct=Math.min(100,((i+1)/roadmapSteps.length)*100);roadmapProgress.style.height=pct+'%'}}}),{threshold:.45});roadmapSteps.forEach(s=>roadObserver.observe(s))}

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.matches('.metric'))animateMetric(e.target)}}),{threshold:.25});document.querySelectorAll('.metric').forEach(x=>observer.observe(x));
function animateMetric(el){const node=el.querySelector('[data-count]');if(!node||node.dataset.done)return;node.dataset.done='1';const target=Number(node.dataset.count);let n=0;const tick=()=>{n+=Math.ceil(target/35);if(n>=target){n=target;node.textContent=n+'+'}else{node.textContent=n;requestAnimationFrame(tick)}};tick()}

const priceModal=document.getElementById('priceModal');const viewInvestment=document.getElementById('viewInvestment');const closeInvestment=document.getElementById('closeInvestment');if(viewInvestment&&priceModal){viewInvestment.addEventListener('click',()=>priceModal.classList.add('open'));closeInvestment?.addEventListener('click',()=>priceModal.classList.remove('open'));priceModal.addEventListener('click',e=>{if(e.target===priceModal)priceModal.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')priceModal.classList.remove('open')});document.getElementById('modalBook')?.addEventListener('click',()=>priceModal.classList.remove('open'))}

form.addEventListener('submit',async e=>{e.preventDefault();if(!chosenTime){selectedSlot.style.color='#ff7c7c';selectedSlot.textContent='Please select a time slot';return}const data=Object.fromEntries(new FormData(form).entries());const submit=form.querySelector('.submit-btn');submit.disabled=true;submit.innerHTML='Submitting…';try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,booking_date:chosenDate,booking_time:chosenTime})});const out=await r.json();if(!r.ok)throw new Error(out.error||'Booking failed');showSuccess(out)}catch(err){alert(err.message)}finally{submit.disabled=false;submit.innerHTML='Request My Call <span>→</span>'}});
function showSuccess(out){const title=toast.querySelector('b'),small=toast.querySelector('small');title.textContent='Call request confirmed';small.innerHTML=`Booking ID: <b>${out.booking.public_id}</b> · <a href="${out.calendar_url}" target="_blank">Add to Calendar</a>${out.whatsapp_url?` · <a href="${out.whatsapp_url}" target="_blank">WhatsApp Dinesh</a>`:''}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),12000);form.reset();chosenTime='';updateSlotLabel();loadAvailability()}
document.querySelector('.menu-toggle').addEventListener('click',()=>{const nav=document.querySelector('nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='78px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px';nav.style.background='#fff';nav.style.flexDirection='column';nav.style.borderBottom='1px solid #dce5f3'});loadAvailability();
