const form=document.getElementById('bookingForm');const selectedSlot=document.getElementById('selectedSlot');const toast=document.getElementById('toast');const slots=document.querySelectorAll('.slots button');const dates=document.querySelectorAll('.date-btn');let chosenDate='Mon, Aug 17';let chosenTime='';

dates.forEach(btn=>btn.addEventListener('click',()=>{dates.forEach(x=>x.classList.remove('active'));btn.classList.add('active');chosenDate=btn.dataset.date;updateSlotLabel()}));
slots.forEach(btn=>btn.addEventListener('click',()=>{slots.forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');chosenTime=btn.dataset.time;updateSlotLabel()}));
function updateSlotLabel(){selectedSlot.textContent=chosenTime?`${chosenDate} • ${chosenTime}`:'Select a time slot'}

document.querySelectorAll('.process-item').forEach(item=>item.addEventListener('click',()=>{document.querySelectorAll('.process-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');document.getElementById('stepNumber').textContent=item.dataset.step.padStart(2,'0')}));

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.matches('.metric'))animateMetric(e.target)}}),{threshold:.25});document.querySelectorAll('.metric').forEach(x=>observer.observe(x));
function animateMetric(el){const node=el.querySelector('[data-count]');if(!node||node.dataset.done)return;node.dataset.done='1';const target=Number(node.dataset.count);let n=0;const tick=()=>{n+=Math.ceil(target/35);if(n>=target){n=target;node.textContent=n+'+'}else{node.textContent=n;requestAnimationFrame(tick)}};tick()}

form.addEventListener('submit',e=>{e.preventDefault();if(!chosenTime){selectedSlot.style.color='#d64242';selectedSlot.textContent='Please select a time slot';return}const data=new FormData(form);const subject=`USA Job Marketing Call Request — ${data.get('name')}`;const body=[`Candidate Name: ${data.get('name')}`,`Current Country: ${data.get('country')}`,`Visa Type: ${data.get('visa')}`,`WhatsApp: ${data.get('whatsapp')}`,`Requirement: ${data.get('requirement')}`,`Preferred Slot: ${chosenDate} • ${chosenTime}`,`Brief Requirement: ${data.get('message')||'Not provided'}`,``,`Submitted via USA Job Application Marketing website.`].join('\n');window.location.href=`mailto:dineshmca500@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),6500);form.reset();slots.forEach(x=>x.classList.remove('selected'));chosenTime='';updateSlotLabel()});

document.querySelector('.menu-toggle').addEventListener('click',()=>{const nav=document.querySelector('nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='78px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px';nav.style.background='#fff';nav.style.flexDirection='column';nav.style.borderBottom='1px solid #dce5f3'});
